FROM python:3.10-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY backend/app.py .
COPY frontend/templates/ ./templates/
COPY frontend/static/ ./static/

EXPOSE 5000

CMD ["python", "app.py"]
