FROM python:3.10-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY src/ ./src/
COPY models/registry/latest/ ./models/registry/latest/

EXPOSE 8080

CMD ["python", "-m", "src.serving.serve"]
